import part_data
import os
from string import Template

output_dir = os.getenv('PB_OUTPUT_DIR', "../../../GameData/RP-1/")

avionics_header = """
//*********************************************************************************************
//  AVIONICS CONFIGURATION
//	This adds avionics and kos modules to parts which have parameters set in JSON
//  
//	DO NOT EDIT THIS FILE DIRECTLY!!!
//	This file is generated from the RP-1 Parts Browser
//
//*********************************************************************************************
"""

avionics_config_template = Template("""
@PART[${name}]:FOR[RP-0]
{
    %MODULE[ModuleAvionics]
    {
        %massLimit = ${mass}
        %interplanetary = ${interplanetary}${toggleable}${disabledkW}
    }${kos}
}""")
toggleable_template = Template("""
        %toggleable = ${toggleable}""")
disabledkW_template = Template("""
        %disabledkW = ${disabledkW}""")
kos_template = Template("""
    %SetupKOS = ${kos}""")

def generate_avionics(parts):
    part_configs = ""
    for part in parts:
        try: avionics = part['avionics']
        except KeyError: avionics = None
        if avionics is not None:
            part_configs += generate_avionics_config(part)
    text_file = open(output_dir + "Avionics_Auto.cfg", "w", newline='\n')
    text_file.write(avionics_header)
    text_file.write(part_configs)
    text_file.close()
        
def generate_avionics_config(part):
    mass = 0
    interplanetary = True
    kos = ''
    toggleable = None
    disabledkW = 0
    try: mass = part['avionics']['massLimit']
    except KeyError: print("Error generating avionics configs! Part " + part['name'] + " is missing massLimit.")
    try: interplanetary = part['avionics']['interplanetary']
    except KeyError: pass
    try: toggleable = part['avionics']['toggleable']
    except KeyError: pass
    try: disabledkW = part['avionics']['disabledkW']
    except KeyError: pass
    try: kos = part['avionics']['SetupKOS']
    except KeyError: pass

    if toggleable is not None:
        toggleable = toggleable_template.substitute(toggleable=toggleable)
    else: toggleable = ''
    if disabledkW > 0:
        disabledkW = disabledkW_template.substitute(disabledkW=disabledkW)
    else: disabledkW = ''
    if len(kos) > 0:
        kos = kos_template.substitute(kos=kos)
    
    return avionics_config_template.substitute(name=part['name'], mass=mass, interplanetary=interplanetary, toggleable=toggleable, disabledkW=disabledkW, kos=kos)

