import part_data
import os
from string import Template

output_dir = os.getenv('PB_OUTPUT_DIR', "../../../GameData/RP-1/Tooling/")

tooling_config_header = """
//*********************************************************************************************
//  TOOLING CONFIGURATION
//	This adds tooling to parts which have parameters set in JSON
//  
//	DO NOT EDIT THIS FILE DIRECTLY!!!
//	This file is generated from the RP-1 Parts Browser
//
//*********************************************************************************************
"""

tooling_config_template = Template("""
@PART[${name}]:FOR[RP-0]
{
    %MODULE[ModuleToolingDiamLen]
    {
        %toolingType = ${toolingType}
        %partDiameter = ${partDiameter}
        %partLength = ${partLength}
    }
}""")

def generate_tooling(parts):
    part_configs = ""
    for part in parts:
        try: tooling = part['tooling']
        except KeyError: tooling = None
        if tooling is not None:
            part_configs += generate_tooling_config(part)
    text_file = open(output_dir + "Tooling_Auto.cfg", "w", newline='\n')
    text_file.write(tooling_config_header)
    text_file.write(part_configs)
    text_file.close()
        
def generate_tooling_config(part):
    toolingType = 'TypeMissing'
    partDiameter = 0
    partLength = 0

    try: toolingType = part['tooling']['toolingType']
    except KeyError: print("Error generating tooling configs! Part " + part['name'] + " is missing toolingType.")
    try: partDiameter = part['tooling']['partDiameter']
    except KeyError: print("Error generating tooling configs! Part " + part['name'] + " is missing partDiameter.")
    try: partLength = part['tooling']['partLength']
    except KeyError: print("Error generating tooling configs! Part " + part['name'] + " is missing partLength.")
    
    return tooling_config_template.substitute(name=part['name'], toolingType=toolingType, partDiameter=partDiameter, partLength=partLength)

