import part_data
import os
from string import Template

training_header = """
//****************************************************************************************
//  ENTRY COST MODIFIERS
//	This adds training times for parts which have parameters set in JSON
//
//	DO NOT EDIT THIS FILE DIRECTLY!!!
//	This file is generated from RP-1 Parts Browser
//
//****************************************************************************************

@TRAININGTIMES
{
"""

output_dir = os.getenv('PB_OUTPUT_DIR', "../../../GameData/RP-1/Tree/")
module_part_config_template = Template("    ${name} = ${training}\n")
training_footer = "}"

def generate_training(parts):
    training_configs = ""
    for part in parts:
        try: training = part['training']
        except KeyError: training = None
        if training is not None:
            training_configs += module_part_config_template.substitute(name=part['name'].replace('_','-').replace('.','-').replace('?',' '), training=training)
    text_file = open(output_dir + "Training_Auto.cfg", "w", newline='\n')
    text_file.write(training_header)
    text_file.write(training_configs)
    text_file.write(training_footer)
    text_file.close()
        